#!/bin/sh
MODULE="scull"
DEVICE="scull"
MAJOR=$(awk "\\$2==\"$module\" {print \\$1}" /proc/devices)
MINOR=0
#remove stale device files
rm -r /dev/${DEVICE}[0-3]
#insert driver with all arguments
insmod ./$MODULE.ko $*
#create the device files
for i in `seq 0 3`
do
	mknod /dev/${DEVICE}$i c $MAJOR $MINOR 
done

